name: Update Portfolio Site

on:
  push:
    branches:
      - main
  release:
    types: [published]

# using env to define vars in the jobs
env:
  PORTFOLIO_REPO: "peterbenoit.github.io"
  PORTFOLIO_REPO_URL: "https://peterbenoit:${{ secrets.PAT_FOR_PORTFOLIO_REPO }}@github.com/peterbenoit/${{ env.PORTFOLIO_REPO }}"
  GIT_USER_NAME: "peterbenoit"
  GIT_USER_EMAIL: "peterbenoit@gmail.com"
  FILE_TO_UPDATE: "./getViewport.js"
  DESTINATION_PATH: "./portfolio/js/getViewport.js"
  COMMIT_MESSAGE: "Update getViewport in portfolio"

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Clone Portfolio Repo
        run: |
          git clone ${{ env.PORTFOLIO_REPO_URL }} portfolio
          cd portfolio
          git config user.name "${{ env.GIT_USER_NAME }}"
          git config user.email "${{ env.GIT_USER_EMAIL }}"

      - name: Copy Updated Library
        run: cp ${{ env.FILE_TO_UPDATE }} ${{ env.DESTINATION_PATH }}

      - name: Commit and Push Changes
        run: |
          cd portfolio
          git add .
          git commit -m "${{ env.COMMIT_MESSAGE }}"
          git push ${{ env.PORTFOLIO_REPO_URL }}
